/*
* MiP_Parameters.h
**  Created on: Jul 3, 2014
*      Author: caseykuhns
*/

#ifndef MIP_PARAMETERS_H_
#define MIP_PARAMETERS_H_

enum Position{
	FACE_UP = 0x00,
	FACE_DOWN = 0x01
};

enum Movement{
	FWD = 0x00,
	BWD = 0x01
};

enum Parameters{
	BATTERY_LEVEL,
	ORIENTATION,

	WEIGHT_UPDATE,

	CHEST_LED_RED,
	CHEST_LED_GREEN,
	CHEST_LED_BLUE,
	CHEST_LED_TIME_ON,
	CHEST_LED_TIME_OFF,

	HEAD_LED_1,
	HEAD_LED_2,
	HEAD_LED_3,
	HEAD_LED_4,

	RADAR_MODE,

	ENABLE_GESTURE_DETECT = 0x02,
	DISABLE_GESTURE_DETECT = 0x00,
	ENABLE_RADAR_DETECT = 0x04,
	DISABLE_RADAR_DETECT = 0x00,
	
	MIP_DETECCTION_ID,
	MIP_DETECTION_POWER,

	ENABLE_IR_CONTROL = 0x01,
	DISABLE_IR_CONTROL = 0x00,

	MIN_VOLUME = 0,
	MAX_VOLUME = 7,

	VERSION_VOICECHIP,
	VERSION_HARDWARE,
};

enum GameMode{
	UNKNOWN = -1,
	APP = 0x01,
	PLAY_BACK = 0x02,
	TRACKING = 0x03,
	DANCE = 0x04,
	DEFAULT_MODE = 0x05,
	STACK = 0x06,
	TRICKS = 0x07,
	ROAM = 0x08
};

enum GetUp{
	FRONT = 0x00,
	BACK = 0x01,
	BOTH = 0x02
};

enum LEDState{
	OFF,
	ON,
	BLINK_SLOW,
	BLINK_FAST
};

enum LEDColor{
	RED,
	GREEN,
	BLUE
};

enum Commands{
	PLAY_SOUND = 0x06,
	SET_POSITION = 0x08,
	DETECTION_MODE = 0x0A,
	SET_IR_CONTROL_STATUS = 0x10,
	GET_IR_CONTROL_STATUS = 0x11,
	GET_SW_VERSION = 0x14,
	SET_VOLUME = 0x15,
	GET_VOLUME = 0x16,
	GET_VOICE_HW_VERSION = 0x19,
	GET_HW_VERSION = 0x19,
	GET_CLAPS_DETECTED = 0x1D,
	SET_CLAP_DETECTION = 0x1E,
	GET_CLAP_DETECTION = 0x1F,
	GET_UP = 0x23,
	DRIVE_FWD_WITH_DISTANCE = 0x70,
	DRIVE_BWD_WITH_DISTANCE = 0x70,
	DRIVE_FWD_WITH_TIME = 0x71,
	DRIVE_BWD_WITH_TIME = 0x72,
	TURN_LEFT_BY_ANGLE = 0x73,
	TURN_RIGHT_BY_ANGLE = 0x74,
	SET_GAME_MODE = 0x76,
	STOP = 0x77,
	GET_GAME_MODE = 0x82,
	GET_CHEST_LED = 0x83,
	SET_CHEST_LED = 0x84,
	RESET_ODOMETER = 0x86,
	FLASH_CHEST_LED = 0x89,
	SET_HEAD_LEDS = 0x8A,
	GET_HEAD_LEDS = 0x8B,
	SLEEP = 0xFA,
	SET_DISCONNECT_APP = 0xFE
};

enum Comms{
	MAX_RETRIES = 20,
	BAUD_RATE = 115200,
	INIT_STRING = 0xFF
};
#endif /* MIP_PARAMETERS_H_ */
